/**
 * The one endpoint that accepts a photo.
 *
 * `POST` a multipart form with `file`, `houseId`, and optionally one of
 * `placeId` or `sectionId`. Everything a photo can hang off — the house
 * gallery, a place, a guide section — comes through here, so the ownership
 * check and the count limits are written once.
 *
 * ```
 * const form = new FormData();
 * form.set("file", file);
 * form.set("houseId", houseId);
 * const response = await fetch("/api/upload", { method: "POST", body: form });
 * const body = await response.json();
 * //  201 -> { id, url, pathname }
 * //  4xx -> { error }   — the message is written to be shown as-is
 * ```
 *
 * ### A route handler, not a Server Action
 *
 * An upload is a file and a progress bar, not a form submit, and a route
 * handler is the only thing here that streams a multipart body without the
 * Server Action body limit in the way. It also means the browser can send
 * several files at once from one `<input multiple>` — which is exactly why the
 * limit check below runs under a row lock.
 *
 * ### Authorisation happens before anything is read
 *
 * The session names the owner; the payload names the house. The house is then
 * loaded *by both*, and a place or section is loaded by its own id **and** the
 * house id, so a person editing the ids in the request cannot attach a photo to
 * a house that is not theirs. Every refusal is the same 403 with the same
 * sentence — which id was wrong is not something a caller gets to learn.
 *
 * `getSession()` rather than `requireOwner()`: `requireOwner()` redirects to
 * `/sign-in`, and a redirect answered to a `fetch` is HTML where the caller
 * expects JSON. Both come from `lib/session.ts`, which stays the only place
 * this app reads auth.
 */

import { revalidatePath } from "next/cache";
import { and, count, eq, isNull, sql, type SQL } from "drizzle-orm";
import { z } from "zod";

import { db } from "@/db";
import { guideSections, houses, images, places } from "@/db/schema";
import { getSession } from "@/lib/session";
import { isStorageError, remove, save, MAX_BYTES } from "@/lib/storage";

/* ============================================================
   LIMITS
   ============================================================ */

/** Photos in the house gallery. The strip on `/h/[slug]` is a scroll, not a book. */
const GALLERY_LIMIT = 12;

/** A place shows the beach; a guide section shows the gate. One photo each. */
const SINGLE_LIMIT = 1;

/**
 * The largest body worth reading into memory. `lib/storage.ts` enforces the
 * real 8MB ceiling on the file itself — this only stops a multi-hundred-megabyte
 * body being buffered before anyone gets to check it.
 */
const MAX_REQUEST_BYTES = MAX_BYTES + 1024 * 1024;

/* ============================================================
   RESPONSES
   ============================================================ */

/** One shape for every failure: `{ error }`, ready to render. */
function fail(status: number, error: string): Response {
  return Response.json(
    { error },
    { status, headers: { "cache-control": "no-store" } },
  );
}

/**
 * The single answer to every authorisation failure — signed out, someone else's
 * house, someone else's place, an id that is not an id. One sentence, no clue
 * as to which of those it was.
 */
function forbidden(): Response {
  return fail(403, "You cannot add a photo there. Sign in as the owner and try again.");
}

/* ============================================================
   READING THE FORM
   ============================================================ */

/** A text field, trimmed. `null` for absent, empty, or a file where text was expected. */
function readText(form: FormData, key: string): string | null {
  const value = form.get(key);
  if (typeof value !== "string") return null;
  const text = value.trim();
  return text === "" ? null : text;
}

/** Ids are generated by Postgres, so anything that is not a UUID is not ours. */
const idSchema = z.uuid();

function isId(value: string | null): value is string {
  return value !== null && idSchema.safeParse(value).success;
}

/* ============================================================
   WHERE THE PHOTO HANGS
   ============================================================ */

/**
 * Which of the three things this photo belongs to. Both foreign keys null is a
 * gallery photo — the schema's rule, restated as a type so the count query and
 * the insert cannot disagree about it.
 */
type Scope =
  | { kind: "gallery"; houseId: string }
  | { kind: "place"; placeId: string }
  | { kind: "section"; sectionId: string };

function scopeWhere(scope: Scope): SQL | undefined {
  if (scope.kind === "place") return eq(images.placeId, scope.placeId);
  if (scope.kind === "section") return eq(images.sectionId, scope.sectionId);
  return and(
    eq(images.houseId, scope.houseId),
    isNull(images.placeId),
    isNull(images.sectionId),
  );
}

function scopeLimit(scope: Scope): number {
  return scope.kind === "gallery" ? GALLERY_LIMIT : SINGLE_LIMIT;
}

/** What to say when there is no room. Names the limit, says what to do about it. */
function fullMessage(scope: Scope): string {
  if (scope.kind === "place") {
    return "A place shows one photo, and this one already has it. Remove that photo before adding another.";
  }
  if (scope.kind === "section") {
    return "A guide section shows one photo, and this one already has it. Remove that photo before adding another.";
  }
  return `The gallery holds ${GALLERY_LIMIT} photos, and it is full. Remove one before adding another.`;
}

/* ============================================================
   POST
   ============================================================ */

/**
 * Always answers JSON.
 *
 * The caller is a `fetch` that reads `response.json()` on every path, so an
 * exception must not be allowed to become the framework's own HTML 500 — that
 * turns "the database was briefly unreachable" into "Unexpected token < in
 * JSON", which is a worse afternoon for everyone. Reading the session can throw
 * too: better-auth queries the database for it, and that is a network call.
 */
export async function POST(request: Request): Promise<Response> {
  try {
    return await upload(request);
  } catch (error) {
    console.error("[upload] unhandled", error);
    return fail(500, "The photo did not save. Try again in a moment.");
  }
}

async function upload(request: Request): Promise<Response> {
  const session = await getSession();
  if (!session) return forbidden();

  // Cheap and first: a body this large is never a photo we would keep.
  const declared = Number(request.headers.get("content-length") ?? "");
  if (Number.isFinite(declared) && declared > MAX_REQUEST_BYTES) {
    return fail(
      413,
      `That photo is too big to upload. Photos have to be under ${Math.floor(MAX_BYTES / (1024 * 1024))}MB — shrink it, or pick another.`,
    );
  }

  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return fail(400, "That upload could not be read. Pick the photo again and retry.");
  }

  const file = form.get("file");
  if (!(file instanceof File)) {
    return fail(400, "No photo arrived. Pick a photo and try again.");
  }

  const houseId = readText(form, "houseId");
  const placeId = readText(form, "placeId");
  const sectionId = readText(form, "sectionId");

  if (!isId(houseId)) return forbidden();
  if (placeId !== null && !isId(placeId)) return forbidden();
  if (sectionId !== null && !isId(sectionId)) return forbidden();

  if (placeId !== null && sectionId !== null) {
    return fail(
      400,
      "A photo belongs to the gallery, a place, or a guide section — not to two of them at once.",
    );
  }

  // The house is loaded by its id *and* the session's owner id. A stranger's
  // house id therefore reads as "no such house", which is all they get told.
  const [house] = await db
    .select({ id: houses.id, slug: houses.slug })
    .from(houses)
    .where(and(eq(houses.id, houseId), eq(houses.ownerId, session.user.id)))
    .limit(1);

  if (!house) return forbidden();

  // Same again for the parent: loaded by its own id and the house's, so a place
  // belonging to another house cannot be named here.
  let scope: Scope = { kind: "gallery", houseId: house.id };

  if (placeId !== null) {
    const [place] = await db
      .select({ id: places.id })
      .from(places)
      .where(and(eq(places.id, placeId), eq(places.houseId, house.id)))
      .limit(1);
    if (!place) return forbidden();
    scope = { kind: "place", placeId: place.id };
  } else if (sectionId !== null) {
    const [section] = await db
      .select({ id: guideSections.id })
      .from(guideSections)
      .where(and(eq(guideSections.id, sectionId), eq(guideSections.houseId, house.id)))
      .limit(1);
    if (!section) return forbidden();
    scope = { kind: "section", sectionId: section.id };
  }

  // Content type, size, and the filename are all `lib/storage.ts`'s business.
  let stored;
  try {
    stored = await save(file, `houses/${house.id}`);
  } catch (error) {
    if (isStorageError(error)) return fail(400, error.message);
    console.error("[upload] save failed", error);
    return fail(500, "The photo did not save. Try again in a moment.");
  }

  let created: { id: string } | null = null;
  try {
    created = await db.transaction(async (tx) => {
      // `<input multiple>` sends several uploads at once. Without this lock
      // every one of them counts the same eleven photos and the gallery
      // quietly grows past twelve. Locking the house row serialises the
      // uploads that could collide and nothing else.
      await tx
        .select({ id: houses.id })
        .from(houses)
        .where(eq(houses.id, house.id))
        .for("update");

      // Counted under the lock, so this answer is still true at the insert.
      const [state] = await tx
        .select({
          used: count(),
          nextPosition: sql<number>`coalesce(max(${images.position}) + 1, 0)`,
        })
        .from(images)
        .where(scopeWhere(scope));

      if ((state?.used ?? 0) >= scopeLimit(scope)) return null;

      const [row] = await tx
        .insert(images)
        .values({
          houseId: house.id,
          url: stored.url,
          pathname: stored.pathname,
          position: state?.nextPosition ?? 0,
          placeId: scope.kind === "place" ? scope.placeId : null,
          sectionId: scope.kind === "section" ? scope.sectionId : null,
        })
        .returning({ id: images.id });

      return row ?? null;
    });
  } catch (error) {
    console.error("[upload] insert failed", error);
    // The row is what makes the file findable. Without one, delete it.
    await remove(stored.pathname);
    return fail(500, "The photo did not save. Try again in a moment.");
  }

  // Full. The file is already written, so take it back out again — the count is
  // checked once, where it is true, rather than twice for the sake of a rare
  // failure that would cost every successful upload a round trip.
  if (!created) {
    await remove(stored.pathname);
    return fail(409, fullMessage(scope));
  }

  // The owner's screens read the photos; so does the guest page.
  revalidatePath("/app", "layout");
  revalidatePath(`/h/${house.slug}`);

  return Response.json(
    { id: created.id, url: stored.url, pathname: stored.pathname },
    { status: 201, headers: { "cache-control": "no-store" } },
  );
}

/* ============================================================
   EVERYTHING ELSE
   ============================================================ */

/**
 * This endpoint writes; nothing else it could be asked to do makes sense.
 * `HEAD` is derived from `GET` by the framework and lands here too.
 */
async function methodNotAllowed(): Promise<Response> {
  return Response.json(
    { error: "Photos are uploaded with POST." },
    { status: 405, headers: { allow: "POST", "cache-control": "no-store" } },
  );
}

export const GET = methodNotAllowed;
export const PUT = methodNotAllowed;
export const PATCH = methodNotAllowed;
export const DELETE = methodNotAllowed;
